version: '3'
services:
  nginx:
    image: nginx:latest # nginx 서비스에서 사용할 도커 이미지
    ports:
      - "80:80"
    volumes:
      - /usr/src/app
      - ./config/nginx:/etc/nginx/conf.d
      - .static_root/:/staticfiles
    depends_on: # 서비스 간의 종속성 표현
      - web
  web:  
    image: highton_web
    build:
      dockerfile : Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 highton.wsgi:application
    volumes:
      - /usr/src/app
    expose:
      - "8000"