# Generated by Django 3.1 on 2022-01-15 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_auto_20220116_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='domains.school'),
        ),
    ]
